### ISSUE TITLE
'Elsa.Api.Client' does not contain 'ElsaClientBuilderOptions'

### ISSUE THREAD

**Issue by KnibbsyMan** [elsa-workflows/elsa-studio#103]
### Elsa 3.0.0 - https://github.com/elsa-workflows/elsa-studio/discussions/102

I have hit an issue when trying to setup the Elsa 3 Studio while following the setup guide on:
https://v3.elsaworkflows.io/docs/installation/elsa-studio-blazorserver

Section:

```
builder.Services.AddRemoteBackend(
    elsaClient => elsaClient.AuthenticationHandler = typeof(AuthenticatingApiHttpMessageHandler),
    options => configuration.GetSection("Backend").Bind(options));
```
Visual Studios shows the following error:
`CS7069 Reference to type 'ElsaClientBuilderOptions' claims it is defined in 'Elsa.Api.Client', but it could not be found`

Looking through the recent commits, I have seen this:
https://github.com/elsa-workflows/elsa-studio/commit/e0f7bdaf7b4b26a56cb3438ee552197cd2f3c88e

Has something been missed during refactoring or am I missing something like an additional Nuget package?

**Comment by mohdali** [comment]
I believe the documentation is already updated with the recent changes. I followed the steps mentioned in the docs and was able to run the studio using Blazor Server without issues. 

Please check and let me know if you are still facing a problem.

**Comment by KnibbsyMan** [comment]
I have just tried to follow the instructions again, exactly as instructed on the website and I am unfortunately still hitting the same issue.

This user is also having the same problem:
https://github.com/elsa-workflows/elsa-core/issues/4740

**Comment by NightWuYo** [comment]
@mohdali Are you using nuget.org? Or other nuget feed.

**Comment by mohdali** [comment]
Ok after some further investigation the solution is to add explicit reference to Elsa.Api.Client version 3.0.0 in the project file.

`<PackageReference Include="Elsa.Api.Client" Version="3.0.0" />`

**Comment by KnibbsyMan** [comment]
I can confirm this has fixed my issue. Thank you.

Can I request that we either get the documentation updated to cover this or get the applicable "Elsa.Studio" package updated to add "Elsa.Api.Client" as a dependency?
