### ISSUE TITLE
How to disable auto retry while running a workflow in studio?

### ISSUE THREAD

**Issue by NightWuYo** [elsa-workflows/elsa-studio#108]
I heard that Elsa Client uses Polly with a retry count 3, but unable to find the related code.
Would you please share a way to disable auto retry? Or point me to the code.

This auto retry logic is annoying, it always retries from the beginning, even though the first activity was succeeded already.

**Comment by NightWuYo** [comment]
I found the code:

https://github.com/elsa-workflows/elsa-core/blob/0785fa6e42db1be054687d8323d54c5ba71914f2/src/clients/Elsa.Api.Client/Extensions/DependencyInjectionExtensions.cs#L93

Able to do the hack now.
But I think it still needs to be improved, run the workflow onces, leads to 4 times success running of an activity, this is not expected.

**Comment by sfmskywalker** [comment]
This is a great catch, and thank you for the PR. The Run Workflow API call should actually never be retried; only calls to e.g. save a workflow, or load a list of workflows, etc. should be retried in cade of transient HTTP errors. I will investigate if there's a way to dynamically apply the policy based on the outgoing request.

**Comment by sfmskywalker** [comment]
This is now fixed.
