### ISSUE TITLE
Elsa.Studio.Login fail to build

### ISSUE THREAD

**Issue by GeorgeS2019** [elsa-workflows/elsa-studio#147]
![image](https://github.com/elsa-workflows/elsa-studio/assets/49812372/3eee16eb-1e42-4eb1-be4c-60db3502895c)

**Comment by sfmskywalker** [comment]
Hi @GeorgeS2019 , can you provide the steps that leads to this issue? When I try to build the project, it builds with no issue.

**Comment by GeorgeS2019** [comment]
@sfmskywalker 
Thx, I will try find time to try again

**Comment by GeorgeS2019** [comment]
git clone latest, build without problem
