### ISSUE TITLE
Unable to rebuild Elsa.Studio project

### ISSUE THREAD

**Issue by zesmaili** [elsa-workflows/elsa-studio#159]
I downloaded the source of Elsa.Studio version 3.0.5 from github, but I can't "build" it and it displays the errors shown in the image, how can I "build" and run the source?

![elsa studio error](https://github.com/elsa-workflows/elsa-studio/assets/110331566/c9fc46b0-2861-45b8-bcfa-b161f1fe8ed1)

**Comment by zesmaili** [comment]
> To build and run the Elsa.Studio source code, you should follow these general steps:
> 
> 1. Ensure that you have all the prerequisites installed, such as the .NET SDK, Node.js, and npm. These are necessary to build and run the .NET and JavaScript portions of the project.
> 2. Clone the repository from GitHub to your local machine using the following command:
>    ```
>    git clone https://github.com/elsa-workflows/elsa-studio.git
>    ```
> 3. Navigate to the directory where you cloned the repository.
> 4. Restore the .NET dependencies by running:
>    ```
>    dotnet restore
>    ```
> 5. Build the .NET solution by running:
>    ```
>    dotnet build
>    ```
> 6. Navigate to the ClientLib directories for the projects that contain the client-side assets. For example:
>    ```
>    cd src/modules/Elsa.Studio.Workflows.Designer/ClientLib
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    and
>    ```
>    cd src/framework/Elsa.Studio.DomInterop/ClientLib
>    ```
> 7. In each of these directories, run the following commands to restore and build the npm packages:
>    ```
>    npm install
>    npm run build
>    ```
> 8. After successfully building the client-side assets, you can run the server project that hosts the Elsa Studio. Navigate to the server project directory and run:
>    ```
>    dotnet run
>    ```
> 9. If the build is successful, you should be able to access the Elsa Studio in your web browser at the specified URL (usually `http://localhost:5000` or `https://localhost:5001`).
> 
> If you encounter specific errors during these steps, please provide the error messages or screenshots so that I can give you more targeted assistance.
> 
> Since the image link you provided does not display an image, I cannot see the specific errors you are encountering. If you can describe the errors or provide a working link to the image, I can offer more detailed help.

Sorry, it's my fault, I didn't ask my question correctly, I want to run the project in Visual Studio 2022, but it's not possible and an error like : 

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0115	'ExpressionInput.OnInitializedAsync()': no suitable method found to override	Elsa.Studio.Shared (net7.0)	G:\Git\elsa\studio\elsa-studio\src\framework\Elsa.Studio.Shared\Components\ExpressionInput.razor.cs	68	Active

or 

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0115	'MainLayout.OnInitialized()': no suitable method found to override	Elsa.Studio.Shared (net7.0)	G:\Git\elsa\studio\elsa-studio\src\framework\Elsa.Studio.Shared\Layouts\MainLayout.razor.cs	34	Active

**Comment by sfmskywalker** [comment]
Hi @zesmaili , I just tried to download & build 3.0.5, which succeeded with no issue. If you want, you can try from scratch and record the steps you are taking. Perhaps we can see what's going on from there.

**Comment by zesmaili** [comment]
Hi @sfmskywalker , The problem was with the sdk files installed on Windows

**Comment by sfmskywalker** [comment]
Got it. Thanks for letting me know 👍🏻
