### ISSUE TITLE
Run Elsa.Studio.Host.Server Error

### ISSUE THREAD

**Issue by WangJunZzz** [elsa-workflows/elsa-studio#190]
1. pull then latest code
2. run src/hosts/Elsa.Studio.Host.Server
3. go to login page error
![image](https://github.com/elsa-workflows/elsa-studio/assets/25657426/2256b7db-4c90-4223-b83a-d00cdc802b26)

**Comment by systemviin** [comment]
Were you able to get this working? 

edit: Nevermind, figured it out. The "Backend" in appsettings is looking for the server from here: https://v3.elsaworkflows.io/docs/installation/elsa-server
