### ISSUE TITLE
Workflow Activity Blocks Have Insufficient Height and No Padding

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-studio#237]
### Steps to Reproduce
1. Create a new workflow.
2. Drag and drop some activities onto the grid.

### Observed Behavior
- The activity blocks have a small height.
- There is no padding within the activity blocks.

### Expected Behavior
- Activity blocks should have sufficient height to display content clearly.
- There should be appropriate padding within the activity blocks to ensure content is not cramped.

### Screenshots
![image](https://github.com/elsa-workflows/elsa-studio/assets/938393/f1aee5e0-cd4a-4327-b1ba-fa6cd6bbf531)

**Comment by LukasBenner** [comment]
@sfmskywalker How did you verify if this is working? I'm using the Elsa Studio components in my custom application, and updating from version 3.1 to 3.2 caused the issue to appear, rather than disappear.
