### ISSUE TITLE
[Bug] Saving workflow changes after migrating JSON-structure not working correctly

### ISSUE THREAD

**Issue by lanseth** [elsa-workflows/elsa-studio#325]
Hi, I've found some weird bug and I'm not sure if it's related with studio or core engine.

If you open an old flow, studio automatically sends a request which updates its JSON-structure to match current elsa version (as it seems to me). After that, any changes that were made at 3rd depth level and below won't be saved.

This bug always appears with old flows, but my colleagues says that sometimes it appears with new ones too. Perhaps, fixing it would affect both cases.

Representation video - https://youtu.be/t-vLv8aNVyU

Old and new JSON-structure files that might be helpful:
[inner-workflow-new.json](https://github.com/user-attachments/files/17789400/inner-workflow-new.json)
[inner-workflow-old.json](https://github.com/user-attachments/files/17789401/inner-workflow-old.json)

**Comment by sfmskywalker** [comment]
Possibly related: #346

**Comment by sfmskywalker** [comment]
I couldn't import the attached workflows because they contain custom activities not available on my machine. However, based on the described symptoms, the issue appears to be resolved as of commit #eb016e156b9983027a4a99aad9d354f27019dbee.
