### ISSUE TITLE
[Bug] Losing changes at 3rd level of depth and below

### ISSUE THREAD

**Issue by lanseth** [elsa-workflows/elsa-studio#346]
Sometimes changes that have been made at 3rd level of depth and below are not saved. It always happens with a newly created flows and often with already existing flows. I've attached the video which is recorded with a completely clear environment (latest version of studio and server which are installed according to tutorial in documentations).

Might be related to this issue:
https://github.com/elsa-workflows/elsa-studio/issues/325

https://github.com/user-attachments/assets/9f73391f-f056-4caa-9176-9c2854a15722

**Comment by sfmskywalker** [comment]
I reproduced and resolved the issue. The fix is included in commit #eb016e156b9983027a4a99aad9d354f27019dbee.
