### ISSUE TITLE
Bug: Missing variables vertical scroll

### ISSUE THREAD

**Issue by MariusVuscanNx** [elsa-workflows/elsa-studio#42]
If you have many variables. you don't have a vertical scroll so you can reach the variables in the bottom.
Also, no horizontal scroll is present.

![image](https://github.com/elsa-workflows/elsa-studio/assets/96233009/e07eebe9-cdf7-42e7-ba52-7ed7ceb4fa0d)

**Comment by sfmskywalker** [comment]
Fixed via f985f1f561a9cffb882d41be39d8b183f69ba6e3
