### ISSUE TITLE
Enhancement: White labeling

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-studio#52]
There should be a way to customize visual aspects such as the Elsa logo and the title.

**Comment by doubleG7** [comment]
I started to build out a couple menu lists components to extend the current design studio and I started to receive the following error. Seems like the *.entry.js is getting clobbered somehow? 
<img width="1413" alt="image" src="https://github.com/elsa-workflows/elsa-studio/assets/70290710/8fbb8b22-5091-4680-8319-0d25bd376d68">

**Comment by doubleG7** [comment]
I grabbed a fresh repo of the preview and it does the same thing now.... can't figure it out. I did upgrade to dotnet runtime to 7.0.11 across the projects.
