### ISSUE TITLE
Unable to start “Elsa.Studio.Host.Server”

### ISSUE THREAD

**Issue by Mr-CTao** [elsa-workflows/elsa-studio#54]
Hello,
Thank you very much for your open source project. When I cloned this project and tried to run 'Elsa. Studio. Host. Server', I received the following error message in the browser I opened:
(Command line window information)
![image](https://github.com/elsa-workflows/elsa-studio/assets/68688170/bea27335-60fc-4a3c-8a31-6b16c9706f09)
(Browser Information)
![image](https://github.com/elsa-workflows/elsa-studio/assets/68688170/d77ba680-e52d-4206-b23d-159c87556c59)
Configuration information for project operation (appsetting. json):
![image](https://github.com/elsa-workflows/elsa-studio/assets/68688170/1bb66c60-aad2-423c-bb09-78ddf4988092)
(launchSettings.json)：
![image](https://github.com/elsa-workflows/elsa-studio/assets/68688170/13b31bbb-e634-4f7d-a198-63e74432d178)
Can you tell me how to configure it to eliminate the above errors? Thank you very much!

**Comment by sfmskywalker** [comment]
Hi @Mr-CTao , please make sure that you also have an Elsa Workflow Server application running. The Elsa Studio application is a client application that doesn't host workflows itself. Instead, it will try and connect to a workflow server.

Unless, of course, you setup your project to host *both* the studio + the server.

**Comment by sfmskywalker** [comment]
I'll go ahead and close this as "Cannot reproduce", but feel free to continue the conversation. If you are still unable to get the project running, then please provide detailed steps to reproduce the issue. Thank you.
