### ISSUE TITLE
Hi @Mr-CTao , please make sure that you also have an Elsa Workflow Server application running. The Elsa Studio application is a client application that doesn't host workflows itself. Instead, it will try and connect to a workflow server.

### ISSUE THREAD

**Issue by Mr-CTao** [elsa-workflows/elsa-studio#57]
Hi @Mr-CTao , please make sure that you also have an Elsa Workflow Server application running. The Elsa Studio application is a client application that doesn't host workflows itself. Instead, it will try and connect to a workflow server.

Unless, of course, you setup your project to host *both* the studio + the server.

_Originally posted by @sfmskywalker in https://github.com/elsa-workflows/elsa-studio/issues/54#issuecomment-1763368276_

**Comment by sfmskywalker** [comment]
Hi @Mr-CTao , can you please clarify what this issue is about? Do we need to do something, and if yes, what might that be?

**Comment by Mr-CTao** [comment]
Thank you for your previous answer. There are no more questions now, thank you very much!

**Comment by sfmskywalker** [comment]
Awesome, thanks for letting me know!
