### ISSUE TITLE
[FEAT] JavaScript Intellisense

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-studio#8]
The Monaco component needs to be configured to offer intellisense for JS syntax.

**Comment by sNakiex** [comment]
BlazorMonaco is currently lacking support to add ExtraLibs (how it works in the js designer)
I see there is a open PR that enables support for custom languages, which seems like a neat way to extend the intellisense capabilities: https://github.com/serdarciplak/BlazorMonaco/pull/66

**Comment by JochenSteinbrenner** [comment]
Can you give me an estimation when it can be fixed? I'm using a lot of JS scripting and this is a big pro of elsa. Thank you, regards Jochen

**Comment by sfmskywalker** [comment]
Thanks for reaching out. Given the competing priorities and commitments, I can't provide a specific timeline for this feat. However, it's on my radar, and I'll prioritize it accordingly among the other requests. Thanks for your understanding.

**Comment by douglasg14b** [comment]
Is it possible to use the JS lib directly without the hampering/imitation of the blazor ecosystem?

Microsoft themselves make great use of it for their interactive docs 🤔

**Comment by sfmskywalker** [comment]
For sure, and it may have to come down to that. The Blazor Monaco project is a wrapper around Monaco, and we’d have to do something similar in terms of JS Interop.

**Comment by sNakiex** [comment]
I will make a PR this week! But what I did to get codehinting to work is to create a typedefinitionservice in studio.core.
Then in the studio.shared project in ExpressionInput.razor.cs I added a method that will use that service to retrieve the Javascript type edfinition from the backend.

Using JSRuntime.InvokeVoidAsync you can then push the received body to: monaco.languages.typescript.javascriptDefaults.addExtraLib

To receive the javascript hinting for the correct workflow/activity you need the following parameters:
var activityTypeName = EditorContext.ActivityDescriptor.TypeName;
var propertyName = EditorContext.InputDescriptor.Name;
var definitionId = EditorContext.WorkflowDefinition.DefinitionId;

If you are in a hurry and cannot wait on the PR + release you can use the above to get it working.

**Comment by sfmskywalker** [comment]
That’s great! I think it’s ok to await your PR, given that it’s been a long time already without intellisense. It would be amazing to get it back in. Appreciate your efforts!

**Comment by sfmskywalker** [comment]
Many thanks for your PR @sNakiex , it works well and it was merged today 🙌🏻
