### ISSUE TITLE
Switch Activity Switch Type Selection Activity Not Saving

### ISSUE THREAD

**Issue by vnomus** [elsa-workflows/elsa-studio#95]
In the Switch (Flow) Activity the dropdown Input Condition Type always reverts back to the initial list item on Save.
The order of the Type selection is apparently in the order in which the feature is added in the Elsa Server. The Switch Activity is simply saving the first item in the list (in my case this was C Sharp). I got around this by reordering the Use statements in the Elsa Server code ( in my case I moved UseJavascript before UseCSharp) and this at least made the Activity functional again....

https://github.com/elsa-workflows/elsa-studio/assets/1231006/94b6a10b-dd06-431c-a048-d8a82c1a8879

**Comment by sfmskywalker** [comment]
I ran into this issue myself today and found this issue, thanks @vnomus 👍🏻 

It will be fixed via de84dcfadc2a9926df5220591ef347232c257d1d
